"""initial schema

Revision ID: 3d5519635beb
Revises: 
Create Date: 2026-08-16 21:47:38.392485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5519635beb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_precificacao', sa.Enum('percentual', 'fixo', name='tipo_precificacao'), nullable=False),
    sa.Column('valor_precificacao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_sku'), ['sku'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'gerente', 'vendedor', 'caixa', 'estoquista', name='user_role'), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consignacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_inicial', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'vendida_total', 'cancelada', name='status_consignacao'), nullable=False),
    sa.Column('data_retirada', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('criado_por_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_seguranca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Enum('login_falho', 'login_sucesso', 'permissao_negada', 'rate_limit_excedido', name='evento_seguranca'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email_tentativa', sa.String(length=120), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('rota', sa.String(length=255), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada_manual', 'saida_consignacao', 'saida_venda', 'devolucao', name='tipo_movimentacao'), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_movimento', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=30), nullable=True),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos_equipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('registrado_por_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precos_equipe_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_precificacao', sa.Enum('percentual', 'fixo', name='tipo_precificacao_equipe'), nullable=False),
    sa.Column('valor_precificacao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_por_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipe_id', 'produto_id', name='uq_equipe_produto')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_numero', sa.String(length=40), nullable=False),
    sa.Column('nome_cliente', sa.String(length=150), nullable=False),
    sa.Column('telefone_cliente', sa.String(length=30), nullable=False),
    sa.Column('email_cliente', sa.String(length=120), nullable=True),
    sa.Column('obs_cliente', sa.Text(), nullable=True),
    sa.Column('nome_destinatario', sa.String(length=150), nullable=False),
    sa.Column('telefone_destinatario', sa.String(length=30), nullable=True),
    sa.Column('endereco_destinatario', sa.Text(), nullable=False),
    sa.Column('obs_destinatario', sa.Text(), nullable=True),
    sa.Column('total_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=False),
    sa.Column('criado_por_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_pedido_numero'), ['pedido_numero'], unique=True)

    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('consignacao_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['consignacao_id'], ['consignacoes.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_venda')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_pedido_numero'))

    op.drop_table('vendas')
    op.drop_table('precos_equipe_produto')
    op.drop_table('pagamentos_equipe')
    op.drop_table('movimentacoes')
    op.drop_table('logs_seguranca')
    op.drop_table('consignacoes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_sku'))

    op.drop_table('produtos')
    op.drop_table('equipes')
    # ### end Alembic commands ###
